services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    command: node dist/index.js 
    environment:
      - PORT=5000
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - INTERNAL_API_URL=http://backend:5000/api
    env_file:
      - ./frontend/.env.local
