services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: builder
    ports:
      - "5000:5000"
    command: pnpm --filter backend run dev
    environment:
      - PORT=5000
      - REDIS_URI=redis://redis:6379
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/smart_inventory}
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/src:/usr/src/app/backend/src
      - ./backend/package.json:/usr/src/app/backend/package.json
      - ./backend/tsconfig.json:/usr/src/app/backend/tsconfig.json

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: builder
    ports:
      - "3000:3000"
    command: pnpm --filter frontend run dev
    environment:
      - INTERNAL_API_URL=http://backend:5000/api
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
      - ./frontend/public:/usr/src/app/frontend/public
      - ./frontend/package.json:/usr/src/app/frontend/package.json
      - ./frontend/next.config.ts:/usr/src/app/frontend/next.config.ts

volumes:
  mongodb_data:
